name: CI_1
on:
  push:
  pull_request:
  schedule:
      - cron: "*/5 * * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ci_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
